
-- TABELA ESTADO 
CREATE TABLE ESTADO(
ID_ESTADO TINYINT NOT NULL ,
SIGLA CHAR(2) NOT NULL,
NOME_ESTADO VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_ESTADO)
);

-- TABELA CIDADE 
CREATE TABLE CIDADE(
ID_CIDADE SMALLINT NOT NULL,
NOME_CIDADE VARCHAR(50) NOT NULL,
ID_ESTADO TINYINT NOT NULL,
PRIMARY KEY (ID_CIDADE),
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

-- TABELA BAIRRO
CREATE TABLE BAIRRO(
ID_BAIRRO  MEDIUMINT NOT NULL,
NOME_BAIRRO VARCHAR(50) NOT NULL,
ID_CIDADE SMALLINT NOT NULL,
PRIMARY KEY (ID_BAIRRO),
FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);
-- TABELA CEP 
CREATE TABLE CEP(
ID_CEP INT NOT NULL,
ID_BAIRRO MEDIUMINT NOT NULL,
NUMERO_CEP CHAR (8) NOT NULL,
PRIMARY KEY (ID_CEP, ID_BAIRRO),
FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO),
UNIQUE (NUMERO_CEP)
);

-- TABELA TIPO PESSOA
CREATE TABLE TIPO_PESSOA (
ID_PESSOA_TIPO INT NOT NULL,
DESCRICAO VARCHAR(20) NOT NULL,
PRIMARY KEY (ID_PESSOA_TIPO)
);
-- TABELA PESSOA 
CREATE TABLE PESSOA (
ID_PESSOA INT NOT NULL ,
NOME_RZ_SOCIAL VARCHAR(150) NOT NULL,
ID_PESSOA_TIPO int NOT NULL,
PRIMARY KEY (ID_PESSOA),
FOREIGN KEY (ID_PESSOA_TIPO) REFERENCES TIPO_PESSOA(ID_PESSOA_TIPO)
);


-- TABELA PESSOA FISICA
CREATE TABLE PESSOA_FISICA (
ID_PESSOA_FISICA INT NOT NULL,
ID_PESSOA INT NOT NULL ,
CPF VARCHAR(11) NOT NULL UNIQUE,
RG VARCHAR(20) NULL,
DATA_DE_NASCIMENTO VARCHAR (10) NOT NULL,
PRIMARY KEY (ID_PESSOA_FISICA,ID_PESSOA),
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

-- TABELA PESSOA JURIDICA 
CREATE TABLE PESSOA_JURIDICA (
ID_PESSOA_JURIDICA int NOT NULL,
ID_PESSOA INT NOT NULL ,
CNPJ VARCHAR(14) NOT NULL UNIQUE,
INSCRICAO_ESTADUAL VARCHAR (12) NULL,
PRIMARY KEY (ID_PESSOA_JURIDICA,ID_PESSOA),
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

-- TABELA PESSOA ENDEREÇO 
CREATE TABLE PESSOA_ENDERECO(
ID_ENDERECO INT NOT NULL,
ID_PESSOA INT NOT NULL ,
ID_CEP INT NOT NULL,
ID_BAIRRO MEDIUMINT NOT NULL,
LOGRADOURO VARCHAR(100) NOT NULL,
NUMERO_LOGRADOURO SMALLINT NOT NULL,
COMPLEMENTO VARCHAR(50) NULL,
PRIMARY KEY (ID_ENDERECO),
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
FOREIGN KEY (ID_CEP) REFERENCES CEP(ID_CEP),
FOREIGN KEY (ID_BAIRRO ) REFERENCES BAIRRO(ID_BAIRRO)
);

-- TABELA LOJA 
CREATE TABLE LOJA(
ID_LOJA  SMALLINT NOT NULL,
ID_PESSOA INT NOT NULL ,
PRIMARY KEY (ID_LOJA), 
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);



-- TABELA CLIENTE 
CREATE TABLE CLIENTE(
ID_CLIENTE INT NOT NULL,
ID_PESSOA INT NOT NULL ,
DATA_CADASTRO VARCHAR(10) NOT NULL,
EMAIL_CLIENTE VARCHAR (50) NULL,
PRIMARY KEY (ID_CLIENTE),
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);


-- TABELA TIPO TELEFONE 
CREATE TABLE TIPO_TELEFONE(
ID_TIPO_TELEFONE TINYINT NOT NULL,
NOME_TIPO_TELEFONE VARCHAR(15) NOT NULL,
PRIMARY KEY (ID_TIPO_TELEFONE)
);

-- TABELA TELEFONE PESSOA 
CREATE TABLE PESSOA_TELEFONE(
ID_TELEFONE INT NOT NULL,
ID_PESSOA INT NOT NULL,
ID_TIPO_TELEFONE TINYINT NOT NULL,
NUMERO_TELEFONE VARCHAR(11) NOT NULL,
PRIMARY KEY (ID_TELEFONE),
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA),
FOREIGN KEY (ID_TIPO_TELEFONE ) REFERENCES TIPO_TELEFONE(ID_TIPO_TELEFONE )
);



-- TABELA FORNECEDOR 
CREATE TABLE FORNECEDOR(
ID_FORNECEDOR INT NOT NULL,
ID_PESSOA INT NOT NULL ,
DATA_DO_CADASTRO DATE,
PRIMARY KEY (ID_FORNECEDOR),
FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

-- TABELA MARCA  
CREATE TABLE MARCA(
ID_MARCA SMALLINT NOT NULL,
DESCRICAO_MARCA VARCHAR(50) NOT NULL,
PRIMARY KEY (ID_MARCA)
);

-- TABELA  CATEGORIA
CREATE TABLE CATEGORIA(
ID_CATEGORIA  SMALLINT  NOT NULL,
DESCRICAO_CATEGORIA  VARCHAR(50)  NOT NULL,
PRIMARY KEY (ID_CATEGORIA)
);

-- TABELA UNIDADE MEDIDA 
CREATE TABLE UNIDADE_MEDIDA(
ID_UNIDADE_MEDIDA SMALLINT  NOT NULL,
DESCRICAO_UNIDADE_MEDIDA VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_UNIDADE_MEDIDA)
);

-- TABELA PRODUTO 
CREATE TABLE PRODUTO (
ID_PRODUTO INT NOT NULL,
ID_FORNECEDOR INT NOT NULL,
DESCRICAO VARCHAR (100),
ID_MARCA SMALLINT NOT NULL,
ID_CATEGORIA  SMALLINT  NOT NULL,
CODIGO_EAN  CHAR(13)  NULL,
ID_UNIDADE_MEDIDA SMALLINT  NOT NULL,
PRECO_COMPRA DECIMAL (10,2),
PRECO_VENDA DECIMAL (10,2),
PESO  DECIMAL(12,3)  NOT NULL,
QTDE_ESTOQUE INT ,
DATA_CADASTRO DATE,
PRIMARY KEY (ID_PRODUTO),
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR),
FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA(ID_UNIDADE_MEDIDA)
);


-- TABELA PEDIDO CABEÇALHO 
CREATE TABLE PEDIDO_CABECALHO (
ID_PEDIDO INT NOT NULL,
ID_CLIENTE INT NOT NULL ,
VALOR_TOTAL DECIMAL (10,2) NOT NULL,
QTDE_ITENS INT NOT NULL,
VALOR_FRETE DECIMAL(10,2) NULL,
STATUS_PEDIDO VARCHAR(20) NULL,
DATA_PEDIDO DATE NOT NULL,
PRIMARY KEY(ID_PEDIDO),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);


-- TABELA ITENS PEDIDO 
 CREATE TABLE ITENS_PEDIDO (
ID_PEDIDOS_ITENS INT NOT NULL ,
ID_PEDIDO INT NOT NULL,
ID_PRODUTO INT NOT NULL,
QTD MEDIUMINT NOT NULL,
VALOR_ITEM DECIMAL(10,2)  NOT NULL,
SUB_TOTAL DECIMAL(10,2) NOT NULL,
PRIMARY KEY(ID_PEDIDOS_ITENS),
FOREIGN KEY(ID_PEDIDO)REFERENCES PEDIDO_CABECALHO(ID_PEDIDO),
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);


-- TABELA NOTA FISCAL 
CREATE TABLE NOTA_FISCAL (
ID_NOTA BIGINT NOT NULL,
ID_CHAVE_DE_ACESSO CHAR(44) NULL,
NUMERO_SERIE CHAR(9) NULL,
DATA_EMISSAO DATE NOT NULL,
VALOR_TOTAL DECIMAL(12,2)  NOT NULL,
ID_CLIENTE INT NULL,
ID_PEDIDO  INT NULL,
ID_LOJA  SMALLINT NOT NULL,
PRIMARY KEY (ID_NOTA),
UNIQUE (ID_CHAVE_DE_ACESSO),
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO_CABECALHO(ID_PEDIDO),
FOREIGN KEY (ID_LOJA) REFERENCES LOJA(ID_LOJA)
);
	
-- TABELA ITENS NOTA FISCAL 
CREATE TABLE LISTA_PRODUTOS (
ID_ITEM_NF SMALLINT NOT NULL,
ID_NOTA BIGINT NOT NULL,
ID_PRODUTO INT NOT NULL,
PRECO_PRODUTO DECIMAL(12,2)  NOT NULL,
QUANTIDADE_PRODUTO MEDIUMINT NOT NULL,
DESCONTO_PRODUTO DECIMAL(12,2) NULL,
PERCENTUAL_ICMS DECIMAL (10,2) NOT NULL,
VALOR_ICMS DECIMAL(12,2)  NOT NULL,
PRIMARY KEY(ID_ITEM_NF,ID_NOTA),
FOREIGN KEY (ID_NOTA) REFERENCES NOTA_FISCAL(ID_NOTA),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- TABELA FORMA PAGAMENTO 
CREATE TABLE FORMA_PAGAMENTO (
ID_PAGAMENTO TINYINT NOT NULL,
DESCRICAO_PAGAMENTO VARCHAR(50) NOT NULL,
PRIMARY KEY(ID_PAGAMENTO)
);

-- TABELA NF FORMA PAGAMENTO 
CREATE TABLE NF_FORMA_PAGAMENTO(
ID_NOTA  BIGINT NOT NULL,
ID_PAGAMENTO TINYINT NOT NULL,
PRIMARY KEY(ID_NOTA,ID_PAGAMENTO),
FOREIGN KEY (ID_NOTA) REFERENCES NOTA_FISCAL(ID_NOTA),
FOREIGN KEY (ID_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_PAGAMENTO)
);




SHOW tables;
